fpath=($fpath ~/.zsh/completion)

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sirosen/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Key Bindings
bindkey -M vicmd '?' history-incremental-search-backward

# editor
export EDITOR=vim

# functions
source ~/.myfuncs/base.sh

# globus
source ~/.globus-tools/globus_funcs.sh

# git aliases and functions
source ~/.zsh_git

# GO Lang Config
export GOROOT=~/.go/gocompiler
export GOPATH=~/.go/gocode
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# add shellcheck to path
export PATH=$PATH:~/bin/shellcheck
# add rock to path
export PATH=$PATH:~/bin/rock/bin
# add rvm to path
export PATH="$PATH:$HOME/.rvm/bin"
# enable RVM funcs
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
# add firefox to path
export PATH=$PATH:~/bin/firefox

###
# Cosmetics
###

# colorizing
eval "$(dircolors ~/.zsh_dircolors)"
alias ls='ls --color=auto'
alias grep='grep --color=auto'
autoload -U colors && colors

# set prompts
setopt TRANSIENT_RPROMPT
setopt prompt_subst

# set prompt if git is installed and we are in a git repo
precmd () {
    PROMPT="[%*] %{$fg[cyan]%}%~%{$reset_color%} %{$fg[yellow]%}->%{$reset_color%} "
    RPROMPT=""

    if [ -n "$VIRTUAL_ENV" ];
    then
        RPROMPT="(venv:%{$fg[yellow]%}$VIRTUAL_ENV%{$reset_color%})"
    fi

    if [ "$(type rvm &> /dev/null; echo "$?")" -eq 0 ];
    then
        RPROMPT="(rvm:%{$fg[yellow]%}$(rvm current)%{$reset_color%})$RPROMPT"
    fi

    if which git &> /dev/null;
    then
        git status &> /dev/null
        if [ $? -eq 0 ];
        then
            local current_branch="$(git rev-parse --abbrev-ref HEAD)"
            RPROMPT="(branch:%{$fg[red]%}$current_branch%{$reset_color%})$RPROMPT"
        fi
    fi
}
