fpath=($fpath ~/.zsh/completion)

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sirosen/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Key Bindings
bindkey -M vicmd '?' history-incremental-search-backward

# editor
export EDITOR=vim

# functions
source ~/.myfuncs/base.sh

# globus
source ~/.globus-tools/globus_funcs.sh

# git aliases and functions
source ~/.zsh_git

# GO Lang Config
export GOROOT=~/.go/gocompiler
export GOPATH=~/.go/gocode
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# add shellcheck to path, only active after installed
export PATH=$PATH:~/bin/shellcheck

###
# Cosmetics
###

# colorizing
eval `dircolors ~/.zsh_dircolors`
alias ls='ls --color=auto'
alias grep='grep --color=auto'
autoload -U colors && colors

# set prompts
setopt TRANSIENT_RPROMPT
setopt prompt_subst

# set prompt if git is installed and we are in a git repo
precmd () {
    PROMPT="[%*] %{$fg[cyan]%}%~%{$reset_color%} %{$fg[yellow]%}->%{$reset_color%} "
    RPROMPT="%{$fg[blue]%}%n%{$reset_color%}@%{$fg[red]%}%M%{$reset_color%}"

    local promptline_prefix='    '

    local virtualenv_prefix=""
    if [ -n "$VIRTUAL_ENV" ];
    then
        virtualenv_prefix="virtualenv: %{$fg[yellow]%}$VIRTUAL_ENV%{$reset_color%}"
        virtualenv_prefix=$promptline_prefix$virtualenv_prefix$'\n'
    fi

    local git_prefix=""
    if which git > /dev/null 2>/dev/null;
    then
        git status > /dev/null 2>/dev/null
        if [ $? -eq 0 ];
        then
            local current_branch="`git branch | grep "^*" | cut -d " " -f 2-`"
            git_prefix=$promptline_prefix"current branch: %{$fg[red]%}$current_branch%{$reset_color%}"

            local git_remotes=""
            for remote in `git remote show`;
            do
                git_remotes=$git_remotes" (%{$fg[yellow]%}$remote%{$reset_color%})"
            done
            if [ "$git_remotes" != "" ];
            then
                git_prefix=$git_prefix" ;; remotes:"$git_remotes
            fi

            git_prefix=$git_prefix$'\n'
        fi
    fi

    local prompt_prefix=$virtualenv_prefix$git_prefix
    if [ "$prompt_prefix" != "" ]; then prompt_prefix=$'\n'$prompt_prefix; fi
    export PROMPT=$prompt_prefix$PROMPT
    export RPROMPT=$RPROMPT
}
